name: Python Code Style Check

on:
  push:
    paths:
      - "src/**"

jobs:
  code-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10.18"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          # Install main package dependencies
          uv pip install --system pytest flake8 pylint setuptools==75.1.0 sphinx myst-parser sphinx-rtd-theme sphinx-book-theme ipykernel

      - name: Run style checks
        run: |
          bash scripts/utils/style_check.sh
